version: "2.2"
services:
  skoob-postgres:
    image: "postgres:latest"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: skoob_crawler_development
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
  skoob-redis:
    image: redis:6.0.10-alpine
    container_name: skoob-redis
    ports:
      - "6379:6379"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    volumes:
      - redis_data_path:/data:delegated
    healthcheck:
      test: redis-cli ping
      start_period: 10s
      interval: 1s
      timeout: 3s
      retries: 30
volumes:
  skoob-data:
    driver: local
  redis_data_path:
networks:
  default:
    driver: bridge
