# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  skoob_page_size: 1000
  secret_key_base: 383502243332126ed75eb34186200f1338e8bb659f655c3374ecce16cb0a7fff30e1f72eb268b278a2ff311fe43a5bccc77e38ec2f02e82bd72ef9a68262874c

test:
  skoob_page_size: 1000
  secret_key_base: 599906fa24f42ab08d156a67f15e40656b647a28529f98e2f94b20c3e72349c2182534bde307ba208691de7b4fb573d85bde8bb31034120eb6a212beaaabe38c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  skoob_page_size: 1000
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
